name: Validation & Versioning

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint:
    name: Run Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Run lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1.5

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Run make test
        run: make test

  tag:
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/develop'
    name: Tag version
    runs-on: ubuntu-latest
    needs: test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get current branch
        id: branch
        run: |
          echo "branch_name=${GITHUB_REF#refs/heads/}" >> $GITHUB_OUTPUT

      - name: Read current version
        id: read_version
        run: |
          version=$(cat version.txt)
          echo "Current version: $version"
          echo "version=${version#v}" >> $GITHUB_OUTPUT

      - name: Increment version
        id: bump
        run: |
          VERSION="${{ steps.read_version.outputs.version }}"

          IFS='.' read -r MAJOR MINOR PATCH <<< "$VERSION"
          PATCH=$((PATCH + 1))

          if [[ "${{ steps.branch.outputs.branch_name }}" == "develop" ]]; then
            NEW_VERSION="v$MAJOR.$MINOR.$PATCH-alpha"
          else
            NEW_VERSION="v$MAJOR.$MINOR.$PATCH"
          fi

          echo "new_version=$NEW_VERSION" >> $GITHUB_OUTPUT

      - name: Update version.txt
        run: |
          RAW_VERSION="${{ steps.read_version.outputs.new_version }}"
          # Remove pre-release suffix if present
          CLEAN_VERSION="${RAW_VERSION%%-*}"

          echo "$CLEAN_VERSION" > version.txt

      - name: Commit updated version.txt
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add version.txt
          git commit -m "Bump version to ${{ steps.bump.outputs.new_version }}"
          git push

      - name: Tag the commit
        run: |
          git tag -a "${{ steps.bump.outputs.new_version }}" -m "Release ${{ steps.bump.outputs.new_version }}"
          git push origin "${{ steps.bump.outputs.new_version }}"
