name: CI/CD Pipeline

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint:
    name: Run Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.1.5

  test:
    name: Run Tests
    runs-on: ubuntu-latest
    needs: lint

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "1.24"

      - name: Run make test
        run: make test

      - name: Annotate uncovered lines in PR diff
        if: github.event_name == 'pull_request'
        uses: slhck/go-coverage-action@v1.0.0
        with:
          coverage-file: coverage.txt
          token: ${{ secrets.GITHUB_TOKEN }}
          threshold: 70 # optional: fail if under 70%
