name: Golang Lint

on:
  push:
    branches:
      - '**'  # Run on every branch
  pull_request:
    branches:
      - main
      - develop

jobs:
  lint:
    name: Run golangci-lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.24'  

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2.1.5
        with:
          version: v2.1.5
